### ISSUE TITLE
Soteria & Hammock

### ISSUE THREAD

**Issue by johnament** [javaee-security-spec/soteria#18]
Hi, I'm interested in making sure Soteria works with Hammock.  Looking at your build output, looks like I just need the appropriate JARs on the classpath.  Anything else you can think of to make it work?

**Comment by arjantijms** [comment]
Hi John,

Did you already tried something and is there anything not working?

In addition to the jars on the class path (api and impl) you may need one of the files shown here: https://github.com/javaee-security-spec/soteria/tree/master/test/app-mem/src/main/webapp/WEB-INF

Specifically JBoss has a kind of omission where it needs a marker file in order to allow custom security code to be installed. This is a quick workaround for a limitation of sorts in JBoss, which is said to be fixable only with the new JBoss security sub-system Elytron.

For GlassFish there's mandatory group to role mapping by default, but this can be disabled in the GlassFish admin console. With Payara this can also be disabled using the `glassfish-web.xml` descriptor.

Other than that nothing special should be needed.

**Comment by johnament** [comment]
Hi Arjan,

No, I didn't try it yet.  Mostly because its vague enough that I'm not sure where to start.  So Hammock doesn't have a servlet deployment per se, its just an uber-jar.  There's no web.xml processing.  So I suspect I'll need to do something special to register the security domain.

Or is there some servlet integration I can deploy that will enable it?

**Comment by arjantijms** [comment]
Is there a request to a Servlet at all? The current iteration of JSR 375/Soteria only works for Servlets (including JAX-RS, in the most common setup where it's fronted by a dispatcher Servlet).

It shouldn't matter so much if its a war or uberjar, but the current `HttpAuthenticationMechanism` is tailored for HTTP calls to a Servlet. Other remote calls (such as JCA inflow or remote EJB) are not supported at the moment.

In the uberjar situation, do you use an embedded Servlet container such as Jetty, Undertow or perhaps Tomcat?

**Comment by keilw** [comment]
@johnament @arjantijms Any progress on this?

**Comment by arjantijms** [comment]
@keilw no progress, I'm provisionally closing this for now, but if anyone wants or can continue this it can be re-opened of course.
