### ISSUE TITLE
How can I test it

### ISSUE THREAD

**Issue by gilbertoca** [javaee-security-spec/soteria#4]
Hi, @arjantijms!
Sorry, it is not a issue but just a question that (searching on google)I could not find.

I've set it up this way:

``` xml
       <!-- SECURITY -->
        <!-- Needed until Java EE 8-->
        <dependency>        
            <groupId>javax.security</groupId>
            <artifactId>javax.security-api</artifactId>
            <version>1.0-m01-SNAPSHOT</version>
        </dependency>        
        <dependency>
            <groupId>org.glassfish.soteria</groupId>
            <artifactId>soteria</artifactId>
            <version>1.0-m01-SNAPSHOT</version>
        </dependency>
```

I've read [you article](http://arjan-tijms.omnifaces.org/p/whats-new-in-java-ee-security-api-10.html) and it uses -Is the omminfaces one another option?

``` xml
        <dependency>
            <groupId>org.omnifaces</groupId>
            <artifactId>soteria</artifactId>
            <version>1.0-m01-SNAPSHOT</version>
        </dependency>
```

But the examples one uses the first option. Can you help me?

In both case I get:

``` bash
Failure to find javax.security:javax.security-api:jar:1.0-m01-SNAPSHOT
```

from maven.

**Comment by arjantijms** [comment]
First of all, thanks for looking at Soteria :)

The dependencies are now indeed problematic. Since Oracle's activity declined, it's not as easy for the non-Oracle staff to push snapshots to the Oracle maven repo, let alone do milestone releases at Maven central.

The examples in the Soteria project are now configured to run against a server that has already been updated with Soteria. E.g. for Payara that would mean putting the full soteria jar (api + impl) in the /modules folder and then deleting the OSGi cache for the domain you're using.

The org.omnifaces was a temporary workaround, but it proved to be too cumbersome to change the group ID every time, do a publish, then change it back. I'll remove that from the article (last published version to org.omnifaces is quite a bit older and hasn't been updated).

There are a few options though. I'll update the article too listing them:

* Checkout the github project for Soteria, then in the /imp folder do a ``mvn clean install``. In your code, depend on the impl.

* Use https://jitpack.io - follow their instructions. This is obviously beyond our control and we can't guarantee anything, but they say to dynamically compile maven projects on GitHub and dynamically provide maven dependencies.

* Setup your own local Jenkins with a job to build Soteria and push it to your own local Nexus. This is what I've done personally, but it's obviously more work and a bit over the top if you only want to test once.

Hope this helps for now, and I'll try to make the situation a bit clearer in the article and code. Thanks again for looking at Soteria.

**Comment by gilbertoca** [comment]
> The examples in the Soteria project are now configured to run against a server that has already been updated with Soteria.

So, it means that I can't use it as bundled with my application? Or it was just a setup to the examples?
We are using TomEE 7.
We've decided to use tomee 7.0.0-M3 because currently between all java ee 7 servers it is the one that mimics jetty/tomcat maven plugin development.  And we want to contribute back, by now reporting issues and in near future helping with docs.
Hope we can do the same for Soteria.

**Comment by gilbertoca** [comment]
Unfortunately it doesn't start with TomEE https://gist.github.com/gilbertoca/f498f1545ae047840512d0ee3e7d0a03

**Comment by arjantijms** [comment]
>So, it means that I can't use it as bundled with my application?

You should be able to bundle it as Soteria (just like Ozark/MVC) is being designed to work either when bundled with the application (e.g. for Tomcat) and when bundled with the Server.

Bundling with the application is also used for testing on Java EE 7 servers. As we're not (yet) taking advantage of any EE 8 features from other specs (e.g. no Servlet 4 or CDI 2.0 yet), Soteria can be tested on Java EE 7 servers.

I haven't tested TomEE 7 though. I did test IBM's Liberty, and unfortunately it doesn't work there due to what you could call either a bug or undefined spec behaviour. I'm working with both IBM and Oracle to get the issue resolved, but naturally both don't have infinite resources, so as for now it hasn't been resolved.

Tested at the moment are JBoss (you need WildFly 10.0.0.Final or newer) and Payara (4.1.1.16.1 or newer)

**Comment by arjantijms** [comment]
>Unfortunately it doesn't start with TomEE https://gist.github.com/gilbertoca/f498f1545ae047840512d0ee3e7d0a03

Hmmm, that's a CDI extension error when adding an annotated type:

```
Caused by: java.lang.NullPointerException
        at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at org.apache.webbeans.portable.AnnotatedElementFactory.setAnnotatedType(AnnotatedElementFactory.java:154)
        at org.apache.webbeans.container.BeanManagerImpl.addAdditionalAnnotatedType(BeanManagerImpl.java:1292)
        at org.apache.webbeans.portable.events.discovery.BeforeBeanDiscoveryImpl.addAnnotatedType(BeforeBeanDiscoveryImpl.java:134)
        at org.glassfish.soteria.cdi.CdiUtils.addAnnotatedTypes(CdiUtils.java:94)
```

That's a very early exception, long before any actual security code is tested. I'll take a look here to see if Soteria is doing something wrong or TomEE is. Both JBoss and Payara are using Weld, so this is the first test on OWB ;)

**Comment by gilbertoca** [comment]
Ok, thank you! 
Do you think it deserves a post in the TomEE user list? Or wait until you take a look at it first?

**Comment by arjantijms** [comment]
A post probably wouldn't hurt, Romain is often pretty fast to find the root cause ;) I'll meanwhile try to look myself too.

**Comment by gilbertoca** [comment]
Done http://tomee-openejb.979440.n4.nabble.com/First-try-with-Soteria-jsr-375-td4678375.html

**Comment by arjantijms** [comment]
Great! I'll look into the ID issue Romain mentioned and see if we can get it a little further then. As mentioned above, Soteria hasn't been tested on TomEE at all, so maybe there are more issues. Soteria also uses many Java EE 7 features, and TomEE isn't final yet. Plus some APIs that Soteria depends on are very new in TomEE, and I haven't tested those individually yet (but it's on my list).

**Comment by arjantijms** [comment]
>The examples in the Soteria project are now configured to run against a server that has already been updated with Soteria.

As of https://github.com/javaee-security-spec/soteria/commit/7e01b1c97a3d70ff4e6c773c38d88679a1e71d4a there's are profiles for "provided" (server has dependencies) and 'bundled" (application bundles dependencies). A small thing, but hopefully this will make the examples more clear.

**Comment by arjantijms** [comment]
@gilbertoca 
>We've decided to use tomee 7.0.0-M3 because currently between all java ee 7 servers it is the one that mimics jetty/tomcat maven plugin development.

I did some tests and as it appears TomEE 7.0.0-M3 is slightly too old to run Soteria well. Some of the required base APIs aren't yet available in that version. I tested the current master of TomEE 7.0.0-SNAPSHOT and that one implements all required Java EE 7 APIs with (till so far) only very few bugs.

TomEE 7.0.0-SNAPSHOT can be downloaded here: 

https://repository.apache.org/service/local/artifact/maven/redirect?
r=snapshots&g=org.apache.tomee&a=apache-tomee&v=7.0.0-SNAPSHOT&c=plus&p=zip

When downloading directly from https://repository.apache.org do note that TomEE changed the group id from org.apache.openejb to org.apache.tomee. You need the latter, otherwise you get a really old snapshot.

Also note that I still have to actually update and test Soteria, but just wanted to mention that M3 will not work for sure.

**Comment by gilbertoca** [comment]
I've did the change locally
```java
beforeBean.addAnnotatedType(beanManager.createAnnotatedType(type),  "soteria" + type.getName() );
```
and it starts with no error.

How do I test it? So, running the app-mem-basic and passing this parameters ...
```bash
http://localhost:8080/app-mem-basic/servlet?callerName=reza&password=secret1

```
I get:
```bash
HTTP Status 403 - Access to the requested resource has been denied
```

and nothing in the tomee-embedded log.

**Comment by arjantijms** [comment]
@gilbertoca 

"app-mem-basic" uses the BASIC authentication mechanism, so for that one you can't pass the user name and password as request parameters. When it works, it sends back a header. It's this one that's used: https://github.com/javaee-security-spec/soteria/blob/master/impl/src/main/java/org/glassfish/soteria/mechanisms/BasicAuthenticationMechanism.java

The identity store (@EmbeddedIdentityStoreDefinition) that you see on top of the servlet, is not connected to the URL in any way. It's a "data base" that's used by the authentication mechanism, so the "callerName" from that identity store does not automatically become a URL parameter.

The "app-custom" app does uses an authentication mechanism that takes the name and password from the URL. It uses this mechanism: https://github.com/javaee-security-spec/soteria/blob/master/test/app-custom/src/main/java/test/TestAuthenticationMechanism.java

I started documenting the sample apps here before, but I've yet to port it over to the official repo: https://github.com/arjantijms/mechanism-to-store-x

If your attempt gives you a 403 right away, the authentication mechanism is likely not used at all. Which version of TomEE did you use?

I did a test locally on TomEE 7.0.0-SNAPSHOT from 05-05-2016 and the lower level part of the authentication mechanism is invoked, but then when it tries to obtain a required CDI bean it fails with:

```
javax.enterprise.inject.UnsatisfiedResolutionException: Api type [javax.security.authentication.mechanism.http.HttpAuthenticationMechanism] is not found with the qualifiers 
Qualifiers: [@javax.enterprise.inject.Default(),@javax.enterprise.inject.Any()]
```

Possible in TomEE/OWB ```cdi.current() can only find beans from a single archive, but I've got to check what's going on here.

**Comment by arjantijms** [comment]
>Possible in TomEE/OWB ``cdi.current()`` can only find beans from a single archive, but I've got to check what's going on here.

As it appears, OWB is slightly more strict about the ``Bean`` definition the extension creates. Got the CDI lookup locally working now, but need to do some cleanup and test if it still works on Weld.

Slowly getting there ;)

**Comment by gilbertoca** [comment]
My maven setup https://gist.github.com/gilbertoca/37b8541db96bf8865a8bfface928e91e
I will try with app-custom as well.

**Comment by arjantijms** [comment]
Can you check what the date is for "7.0.0-SNAPSHOT"? Specifically, check if the /lib folder of the TomEE that's used contains the jaspic-api.jar, and if the Tomcat version is a 8.5.x, and not a 8.0.x (you can see this on the default welcome screen at localhost:8080).

If I test here locally with a recent "7.0.0-SNAPSHOT" it hits org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule right away.

Alternatively you could try deploying the app-custom app to a "normal" (non embedded) TomEE 7.0.0-SNAPSHOT.

**Comment by gilbertoca** [comment]
> Can you check what the date is for "7.0.0-SNAPSHOT"? Specifically, check if the /lib folder of the TomEE that's used contains the jaspic-api.jar, and if the Tomcat version is a 8.5.x, and not a 8.0.x (you can see this on the default welcome screen at localhost:8080).

I've checked, it is ok.

> If I test here locally with a recent "7.0.0-SNAPSHOT" it hits org.glassfish.soteria.mechanisms.jaspic.HttpBridgeServerAuthModule right away.

How do you do (to see)?

> 
Alternatively you could try deploying the app-custom app to a "normal" (non embedded) TomEE 7.0.0-SNAPSHOT. 

I've done, see here https://github.com/gilbertoca/soteria/commit/02b0bf2da36ec6e90f893b44d34dae9ffbdc1f6a

```bash
BEM-INF007:soteria (master u+1) $ cd test/app-custom-session/
BEM-INF007:app-custom-session (master u+1) $ mvn -Pbundled clean package tomee:run
```

**Comment by arjantijms** [comment]
>How do you do (to see)?

I just put a break point there ;) (started TomEE in debug mode via IDE, but you need to patch it a little for that since Eclipse doesn't recognise "8.5.0" for Tomcat)

But without my CDI changes you'll also get a CDI exception as soon as you do a request for app-mem-basic. In the stack you should see the exception originating from that class.

app-custom mostly works here, since it requests genuine scanned CDI beans (not ones added by the CDI extension, which fails without my changes).

>I've done, see here gilbertoca@02b0bf2

If you revert all changes to the pom.xml files, then build soteria with -Pbundled, and subsequently copy the war to a TomEE instance, it should work.

This is one thing to check btw, do the wars that are build contain both the javax.security-api-1.0-m01-SNAPSHOT.jar and soteria-1.0-m01-SNAPSHOT.jar?

There's still some changes to be done locally here (there are quite some differences between Weld and OWB), but after that I'll try to create a step by step guide on how to run an app. Alternatively, if you want, you can also try on Payara and JBoss WildFly 10/JBoss EAP 7.

**Comment by arjantijms** [comment]
I added several fixes for TomEE compatibility here: https://github.com/javaee-security-spec/soteria/commit/a47a81d9ae40608c62e5b01f971acb06edc07ca1

I tested "app-mem-form" by deploying it to a regular standalone TomEE 7.0.0-SNAPSHOT from ~05-05-2016 and navigated to http://localhost:8080/app-mem-form/servlet 

TomEE correctly forwarded me to a form, where I entered the test credentials "reza" and "secret1" and after I submitted the form I was redirected back http://localhost:8080/app-mem-form/servlet which displayed some content.

**Comment by gilbertoca** [comment]
Great work, @arjantijms!
It works in both way: maven and standalone. For now I only tested the app-custom-session, but I will check the others one later. Thank you!

**Comment by arjantijms** [comment]
You're welcome @gilbertoca :) Thanks to you too for testing this!

Keep in mind that all of this is in a very early state. TomEE isn't final, the Tomcat it uses is a milestone, and Soteria is not even at its first milestone (currently working towards milestone 1).

But really to happy to hear it starts working now ;)

**Comment by arjantijms** [comment]
>I started documenting the sample apps here before, but I've yet to port it over to the official repo: https://github.com/arjantijms/mechanism-to-store-x

Documentation for the sample apps added as per https://github.com/javaee-security-spec/soteria/commit/cec91c8801de0b7be516994518675c908f3b5bd1

See https://github.com/javaee-security-spec/soteria/tree/master/test

**Comment by arjantijms** [comment]
>The dependencies are now indeed problematic. Since Oracle's activity declined, it's not as easy for the non-Oracle staff to push snapshots to the Oracle maven repo, let alone do milestone releases at Maven central.

Snapshots published to alternative location oss.jfrog.org as per https://github.com/javaee-security-spec/soteria/commit/e901984e2a92dde8c5e897b3186403f8a01d3cbd

See [Soteria impl](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/glassfish/soteria/soteria/1.0-m02-SNAPSHOT/), [JSR375 API](https://oss.jfrog.org/artifactory/oss-snapshot-local/javax/security/javax.security-api/1.0-m02-SNAPSHOT/) and #10 

It all took some time but we're slowly getting there ;)

**Comment by gilbertoca** [comment]
@arjantijms because of the project's deadline, we could not use Soteria (we integrated Apache Shiro). What I'm planing to do is try to reproduce the same behavior(simple user mgm intranet app) with Soteria. I feel I'm not helping much, sorry! I'm not a great programmer, but I'm willing to help in other areas too. Would you mind to list the tasks you guys are needing to, so we then could try to help?

**Comment by arjantijms** [comment]
@gilbertoca Your help and questions were greatly appreciated, thanks again!
