### ISSUE TITLE
domain object security

### ISSUE THREAD

**Issue by JensPiegsa** [javaee-security-spec/soteria#46]
I'm trying to understand which security aspects the new specification wants to cover. Does Soteria provide a concept like *domain object security*? And in more general terms, how are concepts from Apache Shiro, Spring Security ACL, OACC, Keycloak, PAC4J, PicketLink etc. being considered for standardisation?

**Comment by arjantijms** [comment]
The security spec first and foremost covers the two existing artefacts that all (Java EE) servers already implement in some way, namely the "authentication mechanism" (known from Servlet's  FORM, BASIC, etc) and the "identity store" (known from the JAAS LoginModule, and the many Server specific variants of this, see http://arjan-tijms.omnifaces.org/2015/10/how-servlet-containers-all-implement.html)

It effectively standardises these in a modern (CDI) and user friendly (very little setup code needed) version.

It plugs-in to the existing Java EE security backbone, which i.e. is responsible for making sure things HttpServletRequest#isUserInRole and constraints in web.xml work.

Because of a serious shortage of resources, we barely got to consider more advanced concepts from other specs, although we were able to add the feature from Spring Security and others where multiple identity stores can be configured and the system tries them all until one succeeds.

Hope this helps.

**Comment by JensPiegsa** [comment]
@arjantijms Arjan, Thanks for your very comprehensive answer -- very helpful for my understanding. -- Jens
