### ISSUE TITLE
How to test the SecurityContext.authenticate() with wrong Credential?

### ISSUE THREAD

**Issue by zjmtlab** [javaee-security-spec/soteria#55]
I want to verify the negative test case about SecurityContext.authticate(),  pass in wrong password, want to get AuthStatus.FAILURE result.

So I write a Servlet, will get the user/password from request parameters. Then invoke SecurityContext.authticate() method in doGet.  When the client pass wrong password, expect to get AuthStatus.FAILURE.
```
        String username = request.getParameter("name");
        String password = request.getParameter("password");
        Credential credential = new UsernamePasswordCredential(username, new Password(password));
        
        AuthStatus status = securityContext.authenticate(
                request,
                response,
                AuthenticationParameters.withParams()
                    .credential(credential));
```

And I write a TestAuthenticationMechanism.java expect it can work together with EmbeddedIdentityStoreDefinition declared in Servlet. In this HAM, try to get credential from HttpMessageContext, it indeed got the credential in the authticate() process.
```
     public class TestAuthenticationMechanism implements HttpAuthenticationMechanism {
	@Override
	public AuthStatus validateRequest(HttpServletRequest request, HttpServletResponse response, HttpMessageContext httpMessageContext) throws AuthException {
        if (hasCredential(httpMessageContext)) {
            IdentityStoreHandler identityStoreHandler = CDI.current().select(IdentityStoreHandler.class).get();
            return httpMessageContext.notifyContainerAboutLogin(
                    identityStoreHandler.validate(
                    httpMessageContext.getAuthParameters()
                                      .getCredential()));
        }
		return httpMessageContext.doNothing();
	}
	private static boolean hasCredential(HttpMessageContext httpMessageContext) {
	    return 
            httpMessageContext.getAuthParameters().getCredential() != null;
	}
}
```
But the SecurityContext.authticate() always return SUCCESS even with wrong password.
After debug, I found that is because in SecurityContextImpl.authenticate(), if the validate result is not true, it will return the last authentication status,  I don't know why.  And the HAM's validateRequest() will be invoke once before doGet, and because this invoke can't get the credential from HttpMessageContext, so return doNothing(), it is SUCCESS status. I think that is the last authentication status. which be wrongly returned.

Can you please give suggestion about this test case? Thanks very much!

**Comment by arjantijms** [comment]
Thanks so much for this report!

You hit a bug, an oversight of me.

The securityContext.authenticate call will cause the HAM to be called again (2nd time), and it by validating the wrong credentials an auth exception will be thrown:

```
  @Override
    public AuthenticationStatus notifyContainerAboutLogin(CredentialValidationResult result) throws AuthException {
        if (result.getStatus() == VALID) {
            return notifyContainerAboutLogin(
                result.getCallerPrincipal(), 
                result.getCallerGroups());
            
        } else {
            throw new AuthException("Authentication failed with status" + result.getStatus());
        }
    }
```

Now first of all I think we have to re-evalute our usage of AuthException vs returning SEND_FAILURE, but in this case it's an exception.

Now in our test case a LoginToContinueInterceptor happens to be used, which converts the exception into the SEND_FAILURE mentioned above:

```
  try {
            authstatus = (AuthenticationStatus) invocationContext.proceed();
        } catch (AuthException e) {
            authstatus = AuthenticationStatus.SEND_FAILURE;
        }
```

Now in the JASPIC to Java EE Security bridge the last status is normally set, but skipped if there's an exception;

```
        public AuthStatus validateRequest(MessageInfo messageInfo, Subject clientSubject, Subject serviceSubject) throws AuthException {
            
            HttpMessageContext msgContext = new HttpMessageContextImpl(handler, options, messageInfo, clientSubject);
            
            if (cdiPerRequestInitializer != null) {
                cdiPerRequestInitializer.init(msgContext.getRequest());
            }
                
            AuthenticationStatus status = CDI.current()
                                             .select(HttpAuthenticationMechanism.class).get()
                                             .validateRequest(
                                                 msgContext.getRequest(), 
                                                 msgContext.getResponse(), 
                                                 msgContext);
            
            setLastAuthenticationStatus(msgContext.getRequest(), status);
            
            return fromAuthenticationStatus(status);
        }
```

Maybe it's best to set authentication status to SEND_FAILURE here, even though it's technically a little different.

Then in the JASPIC.authenticate call we convert 2 exceptions:

```
			return request.authenticate(response);
		} catch (ServletException | IOException e) {
			throw new IllegalArgumentException(e);
```

And in SecurityContext.authenticate we create the final result as you have seen:

```
    @Override
    public AuthenticationStatus authenticate(HttpServletRequest request, HttpServletResponse response, AuthenticationParameters parameters) {
        
        try {
            if (Jaspic.authenticate(request, response, parameters)) {
                // All servers return true when authentication actually took place 
                return SUCCESS;
            }
            
            // GlassFish returns false when either authentication is in progress or authentication
            // failed (or was not done at all). 
            // Therefore we need to rely on the status we saved as a request attribute
            return getLastAuthenticationStatus(request);
        } catch (IllegalArgumentException e) { // TODO: exception type not ideal
            // JBoss returns false when authentication is in progress, but throws exception when
            // authentication fails (or was not done at all).
            return SEND_FAILURE;
        }
    }
```

In case of the AuthException, your server returned false here, so the last status is returned.

Now why all this convoluted mapping?

The core problem is that `HttpServletRequest.authenticate()`, on which `SecurityContext.authenticate()` builds, is not well enough defined, or not well enough tested by a TCK, since different servers do different things here. I tried to bring this to the attention of the Servlet EG earlier, but did not has success till so far.

My first question to you, which server were you using?

Also a remark, from `AuthStatus status` I see you're using an older version of Soteria. We recently changed this to `AuthenticationStatus status` and FAILURE was recently changed to SEND_FAILURE.

I'm going to add a test case for this and will try to fix the bug/oversight.

Thanks again!

**Comment by arjantijms** [comment]
@zjmtlab 

I hope the bug has been fixed now, let me know if you still encounter issues.

**Comment by zjmtlab** [comment]
Thanks very much for so quickly response!

**Comment by arjantijms** [comment]
You're welcome! :)
