### ISSUE TITLE
The Basic/Form/CustomForm HAM not have @ApplicationScoped

### ISSUE THREAD

**Issue by zjmtlab** [javaee-security-spec/soteria#64]
I found this line in Spec, but seems the Basic/Form/CustomForm HAM in soteria not have these scopes. So I want to know why? Thanks!

"""
All of these beans MUST have the qualifier @Default and the scope @ApplicationScoped, as defined
by the CDI specification.
"""

**Comment by rdebusscher** [comment]
Hi,

They are ApplicationScoped in Soteria, but is is a bit hidden :) A few other people was confused also by this.

The actual addition of the CDI beans is done programmatically in the CDI extension `org.glassfish.soteria.cdi.CdiExtension` because they need to be defined based on the info in the Definition Annotations.

And there they are defined as AppliationScoped.
